before_script:
  - echo "Do before script"

after_script:
  - echo "Do after script"

stages:
  - set_custom_ci_variable
  - testing
  - build
  - deploy

set_custom_ci_variable:
  stage: set_custom_ci_variable
  tags:
    - basic
  only:
    - develop
    - master
  script:
    - |
      # declare variable
      ACCESS_TOKEN="${CI_ACCESS_TOKEN}"
      HEADER="PRIVATE-TOKEN: ${ACCESS_TOKEN}"
      OUTPUT_PATH="./variables"
      ENV=($(cat .env.ci))
      KEY="${CI_COMMIT_REF_NAME}_ENV"
      VALUE=""
      API_VERSION="v4"
      API_URL="${CI_SERVER_URL}/api/${API_VERSION}"
      PROJECT_ID="${CI_PROJECT_ID}"
      UPDATE=false
    - |
      # declare function
      process_value() {
        for value in ${ENV[@]} ; do
          VALUE+="${value}
      "
        done
      }
      fetch_project_variables() {
        echo $FUNCNAME
        curl --request GET "${API_URL}/projects/${PROJECT_ID}/variables" \
          --header "${HEADER}" \
          --output "${OUTPUT_PATH}";
      }
      create_or_update_ci_variable() {
        echo $FUNCNAME
        for i in ${!VARIABLE_KEY_SET[@]}; do
          if [[ ${VARIABLE_KEY_SET[$i]} == $1 ]]; then
            UPDATE=true
            break
          fi
        done
      }
      create_ci_variable() {
        echo $FUNCNAME
        curl --request POST "${API_URL}/projects/${PROJECT_ID}/variables" \
          --header "${HEADER}" \
          --form "key=$1" \
          --form "value=${VALUE}"
      }
      update_ci_variable() {
        echo $FUNCNAME
        curl --request PUT "${API_URL}/projects/${PROJECT_ID}/variables/$1" \
          --header "${HEADER}" \
          --form "value=${VALUE}"
      }
    - |
      # main
      process_value

      fetch_project_variables

      VARIABLE_KEY_SET=(
        $(jq --raw-output '.[].key' ${OUTPUT_PATH})
      )

      create_or_update_ci_variable ${KEY}

      if [[ ${UPDATE} = true ]]; then
        update_ci_variable ${KEY}
      else
        create_ci_variable ${KEY}
      fi

      rm ${OUTPUT_PATH}

test_frontend_install:
  stage: testing
  script:
    - echo "Do test frontend install"

test_backend_install:
  stage: testing
  script:
    - echo "Do test backend install"

build_frontend:
  stage: build
  script:
    - echo "Do build frontend"

build_backend:
  stage: build
  script:
    - echo "Do build backend"

deploy:
  stage: deploy
  script:
    - echo "Do deploy"
