before_script:
  - echo "Before script section"

after_script:
  - echo "After script section"

stages:
  - build
  - test
  - deploy

build1:
  stage: build
  script:
    - echo "Do your build here"

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

test3:
  stage: test
  script:
    - |
      echo "CI_JOB_ID: ${CI_JOB_ID}"
      echo "CI_COMMIT_SHA: ${CI_COMMIT_SHA}"
      echo "CI_COMMIT_SHORT_SHA: ${CI_COMMIT_SHORT_SHA}"
      echo "CI_COMMIT_REF_NAME: ${CI_COMMIT_REF_NAME}"
      echo "CI_REPOSITORY_URL: ${CI_REPOSITORY_URL}"
      echo "CI_COMMIT_TAG: ${CI_COMMIT_TAG}"
      echo "CI_JOB_NAME: ${CI_JOB_NAME}"
      echo "CI_JOB_STAGE: ${CI_JOB_STAGE}"
      echo "CI_JOB_MANUAL: ${CI_JOB_MANUAL}"
      echo "CI_JOB_TRIGGERED: ${CI_JOB_TRIGGERED}"
      echo "CI_JOB_TOKEN: ${CI_JOB_TOKEN}"
      echo "CI_PIPELINE_ID: ${CI_PIPELINE_ID}"
      echo "CI_PIPELINE_IID: ${CI_PIPELINE_IID}"
      echo "CI_PAGES_DOMAIN: ${CI_PAGES_DOMAIN}"
      echo "CI_PAGES_URL: ${CI_PAGES_URL}"
      echo "CI_PROJECT_ID: ${CI_PROJECT_ID}"
      echo "CI_PROJECT_DIR: ${CI_PROJECT_DIR}"
      echo "CI_PROJECT_NAME: ${CI_PROJECT_NAME}"
      echo "CI_PROJECT_TITLE: ${CI_PROJECT_TITLE}"
      echo "CI_PROJECT_NAMESPACE: ${CI_PROJECT_NAMESPACE}"
      echo "CI_PROJECT_PATH: ${CI_PROJECT_PATH}"
      echo "CI_PROJECT_URL: ${CI_PROJECT_URL}"
      echo "CI_REGISTRY: ${CI_REGISTRY}"
      echo "CI_REGISTRY_IMAGE: ${CI_REGISTRY_IMAGE}"
      echo "CI_REGISTRY_USER: ${CI_REGISTRY_USER}"
      echo "CI_REGISTRY_PASSWORD: ${CI_REGISTRY_PASSWORD}"
      echo "CI_RUNNER_ID: ${CI_RUNNER_ID}"
      echo "CI_RUNNER_DESCRIPTION: ${CI_RUNNER_DESCRIPTION}"
      echo "CI_RUNNER_TAGS: ${CI_RUNNER_TAGS}"
      echo "CI_SERVER: ${CI_SERVER}"
      echo "CI_SERVER_URL: ${CI_SERVER_URL}"
      echo "CI_SERVER_HOST: ${CI_SERVER_HOST}"
      echo "CI_SERVER_PORT: ${CI_SERVER_PORT}"
      echo "CI_SERVER_PROTOCOL: ${CI_SERVER_PROTOCOL}"
      echo "CI_SERVER_NAME: ${CI_SERVER_NAME}"
      echo "CI_SERVER_REVISION: ${CI_SERVER_REVISION}"
      echo "CI_SERVER_VERSION: ${CI_SERVER_VERSION}"
      echo "CI_SERVER_VERSION_MAJOR: ${CI_SERVER_VERSION_MAJOR}"
      echo "CI_SERVER_VERSION_MINOR: ${CI_SERVER_VERSION_MINOR}"
      echo "CI_SERVER_VERSION_PATCH: ${CI_SERVER_VERSION_PATCH}"
      echo "GITLAB_USER_EMAIL: ${GITLAB_USER_EMAIL}"
      echo "GITLAB_USER_ID: ${GITLAB_USER_ID}"

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
